CREATE TABLE IF NOT EXISTS COMMUNITY_TAGS (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    COMMUNITY_ID INTEGER NOT NULL,
    TAG_NAME VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);