CREATE TABLE IF NOT EXISTS COMMUNITY_COMMENT_INFO (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    PARENT_ID INTEGER DEFAULT NULL,
    DEPTH INTEGER NOT NULL DEFAULT 0 CHECK (DEPTH >= 0),
    POST_ID INTEGER NOT NULL,
    COMMENT_TYPE VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONTENT TEXT NOT NULL CHECK (
        (UPPER(COMMENT_TYPE) = 'TREE' AND LENGTH(CONTENT) <= 10000) OR
        (UPPER(COMMENT_TYPE) = 'THREAD' AND LENGTH(CONTENT) <= 20000)
    ),
    LIKES INTEGER NOT NULL DEFAULT 0,
    DISLIKES INTEGER NOT NULL DEFAULT 0,
    IS_ROOT BOOLEAN NOT NULL DEFAULT FALSE
);