CREATE TABLE IF NOT EXISTS COMMUNITY_USER_LIKE_DISLIKE (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    USER_ID INTEGER NOT NULL,
    POST_ID INTEGER NOT NULL,
    VALUE INTEGER NOT NULL CHECK (VALUE = 1 OR VALUE = -1)
);