CREATE TABLE IF NOT EXISTS COMMUNITY_COMMENT_USER_LIKE_DISLIKE (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    COMMENT_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    VALUE INTEGER NOT NULL CHECK (VALUE = 1 OR VALUE = -1)
);