CREATE TABLE IF NOT EXISTS COMMUNITY_POST_INFO (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    COMMUNITY_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    TAGS VARCHAR(100)[] NOT NULL,
    TITLE TEXT NOT NULL CHECK (LENGTH(TITLE) <= 500),
    CONTENT TEXT NOT NULL,
    LIKES INTEGER NOT NULL DEFAULT 0,
    DISLIKES INTEGER NOT NULL DEFAULT 0,
    COMMENTS INTEGER NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);