CREATE TABLE IF NOT EXISTS COMMUNITY_INFO (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    OWNER_ID INTEGER NOT NULL,
    TITLE VARCHAR(50) NOT NULL UNIQUE,
    SUBTITLE VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    BANNER_URL TEXT DEFAULT NULL,
    ICON_URL TEXT DEFAULT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);