CREATE TABLE IF NOT EXISTS USER_AUTH (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD CHAR(60) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    IS_BANNED BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_SIGN_IN TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(FIRST_NAME, LAST_NAME)
);