CREATE TABLE IF NOT EXISTS USER_AUTH (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    FIRST_NAME VARCHAR(100) NOT NULL CHECK (CHAR_LENGTH(FIRST_NAME) >= 3 AND FIRST_NAME ~ '^[a-zA-Z0-9_]+$'),
    LAST_NAME VARCHAR(100) NOT NULL CHECK (CHAR_LENGTH(LAST_NAME) >= 3 AND LAST_NAME ~ '^[a-zA-Z0-9_]+$'),
    USERNAME VARCHAR(255) UNIQUE NOT NULL CHECK (CHAR_LENGTH(USERNAME) >= 5 AND USERNAME ~ '^[a-zA-Z0-9_]+$'),
    EMAIL TEXT UNIQUE NOT NULL CHECK (EMAIL ~ '^\S+@\S+\.\S+$'),
    PASSWORD VARCHAR(255) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    IS_BANNED BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_SIGN_IN TIMESTAMPTZ DEFAULT NULL,

    UNIQUE(FIRST_NAME, LAST_NAME)
);